version: "3.9"

services:
  duckdns-updater:
    build: .
    dns:
      - 1.1.1.1
      - 8.8.8.8
    container_name: duckdns-updater
    environment:
      DUCKDNS_DOMAIN: DUCKDNS_DOMAIN
      DUCKDNS_TOKEN: DUCKDNS_TOKEN
    restart: unless-stopped
